In [5]:
execfile('setting.py')

In [16]:
df_raw=pd.read_csv("/home/piai/Downloads/B2B.csv")
df_raw.head(10)

,Unnamed: 0,invoice,product_code,product_name,quantity,date,unit_price,customer_id,sales,city,...,pop_size,city_type,city_lctn,stock_type,QuantityCanceled,real_quantity,real_sales,margin,quarter,Refund_OX
0,0,539993,22386,JUMBO BAG PINK POLKADOT,10,2021-01-04,1.95,E13313,19.50,Honolulu,...,small,sightseeing,other,consignment,0,10,19.50,1.950,1,0
1,1,560915,22386,JUMBO BAG PINK POLKADOT,10,2021-07-21,2.08,E13313,20.80,Honolulu,...,small,sightseeing,other,consignment,0,10,20.80,2.080,3,0
2,2,545602,22386,JUMBO BAG PINK POLKADOT,1,2021-03-04,1.95,E17315,1.95,New York,...,big,metro,east,consignment,0,1,1.95,0.195,1,0
3,3,548150,22386,JUMBO BAG PINK POLKADOT,1,2021-03-29,1.95,E17315,1.95,New York,...,big,metro,east,consignment,0,1,1.95,0.195,1,0
4,4,554090,22386,JUMBO BAG PINK POLKADOT,2,2021-05-22,2.08,E17315,4.16,New York,...,big,metro,east,consignment,0,2,4.16,0.416,2,0
5,5,559336,22386,JUMBO BAG PINK POLKADOT,2,2021-07-07,2.08,E17315,4.16,New York,...,big,metro,east,consignment,0,2,4.16,0.416,3,0
6,6,546249,22386,JUMBO BAG PINK POLKADOT,6,2021-03-10,1.95,E14606,11.70,San Diego,...,middle,sightseeing,west,consignment,0,6,11.70,1.170,1,0
7,7,551194,22386,JUMBO BAG PINK POLKADOT,1,2021-04-27,2.08,E14606,2.08,San Diego,...,middle,sightseeing,west,consignment,0,1,2.08,0.208,2,0
8,8,556887,22386,JUMBO BAG PINK POLKADOT,2,2021-06-15,2.08,E14606,4.16,San Diego,...,middle,sightseeing,west,consignment,0,2,4.16,0.416,2,0
9,9,557577,22386,JUMBO BAG PINK POLKADOT,2,2021-06-21,2.08,E14606,4.16,San Diego,...,middle,sightseeing,west,consignment,0,2,4.16,0.416,2,0

In [17]:
df=pd.read_csv("/home/piai/Downloads/category ìµœì¢… (1).csv")
df.head(10)

,Unnamed: 0,product_name,stock_type,category
0,0,JUMBO BAG PINK POLKADOT,consignment,"Bags, Luggage & Accessories"
1,1,BLUE POLKADOT WRAP,consignment,Home & Garden
2,2,RED RETROSPOT WRAP,consignment,Home & Garden
3,3,RECYCLING BAG RETROSPOT,consignment,"Bags, Luggage & Accessories"
4,4,RED RETROSPOT SHOPPER BAG,consignment,"Bags, Luggage & Accessories"
5,5,JUMBO BAG RED RETROSPOT,consignment,"Bags, Luggage & Accessories"
6,6,RED RETROSPOT CHILDRENS UMBRELLA,consignment,Home & Garden
7,7,JAM MAKING SET PRINTED,consignment,Home & Garden
8,9,CHILDRENS APRON APPLES DESIGN,consignment,Home & Garden
9,10,PEG BAG APPLES DESIGN,consignment,"Bags, Luggage & Accessories"

In [18]:
df_data=pd.merge(df_raw, df[['product_name','category']],on=['product_name'],how='left')
df_data.columns

Index(['Unnamed: 0', 'invoice', 'product_code', 'product_name', 'quantity',
       'date', 'unit_price', 'customer_id', 'sales', 'city', 'state',
       'pop_thousand', 'land_sq_meter', 'pop_size', 'city_type', 'city_lctn',
       'stock_type', 'QuantityCanceled', 'real_quantity', 'real_sales',
       'margin', 'quarter', 'Refund_OX', 'category'],
      dtype='object')

In [57]:
df_data.to_csv('/home/piai/includecate.csv')

In [ ]:
df_data.to_csv('')

In [20]:
df_data['category']

0         Bags, Luggage & Accessories
1         Bags, Luggage & Accessories
2         Bags, Luggage & Accessories
3         Bags, Luggage & Accessories
4         Bags, Luggage & Accessories
                     ...
276762                            NaN
276763                            NaN
276764                            NaN
276765                            NaN
276766                            NaN
Name: category, Length: 276767, dtype: object

In [22]:
data=df_data[df_data['unit_price']<=10][['product_name','real_quantity','category']]
data.head()

              product_name  real_quantity                     category
0  JUMBO BAG PINK POLKADOT             10  Bags, Luggage & Accessories
1  JUMBO BAG PINK POLKADOT             10  Bags, Luggage & Accessories
2  JUMBO BAG PINK POLKADOT              1  Bags, Luggage & Accessories
3  JUMBO BAG PINK POLKADOT              1  Bags, Luggage & Accessories
4  JUMBO BAG PINK POLKADOT              2  Bags, Luggage & Accessories

In [24]:
data=data.sort_values(by='real_quantity',ascending=False)

In [41]:
rank=pd.DataFrame(data.groupby('product_name')['real_quantity'].sum()).sort_values(by='real_quantity',ascending=False)[0:30]

In [48]:
pd.DataFrame(data.groupby('product_name')['real_quantity'].sum()).sort_values(by='real_quantity',ascending=False)[0:30]

                                     real_quantity
product_name
WORLD WAR 2 GLIDERS ASSTD DESIGNS            36102
JUMBO BAG RED RETROSPOT                      34702
ASSORTED COLOUR BIRD ORNAMENT                33310
WHITE HANGING HEART T-LIGHT HOLDER           29064
POPCORN HOLDER                               23124
VICTORIAN GLASS HANGING T-LIGHT              19633
PACK OF 12 LONDON TISSUES                    19422
PACK OF 72 RETROSPOT CAKE CASES              19275
ASSORTED COLOURS SILK FAN                    19033
BROCADE RING PURSE                           18984
PACK OF 60 PINK PAISLEY CAKE CASES           18597
SMALL POPCORN HOLDER                         17033
JUMBO BAG PINK POLKADOT                      15905
RED  HARMONICA IN BOX                        14646
JUMBO BAG STRAWBERRY                         14588
COLOUR GLASS T-LIGHT HOLDER HANGING          14039
PARTY BUNTING                                13995
HEART OF WICKER SMALL                        13590
ANTIQUE SILVER T-LIGHT GLASS                 12163
LUNCH BAG RED RETROSPOT                      11669
60 TEATIME FAIRY CAKE CASES                  11541
SMALL CHINESE STYLE SCISSOR                  11484
GROW A FLYTRAP OR SUNFLOWER IN TIN           11404
PLACE SETTING WHITE HEART                    11393
JUMBO BAG ALPHABET                           10322
JUMBO BAG APPLES                             10240
PACK OF 72 SKULL CAKE CASES                  10218
TRAVEL CARD WALLET KEEP CALM                 10099
MINI PAINT SET VINTAGE                        9835
JUMBO STORAGE BAG SUKI                        9610

In [47]:
pd.merge(rank,data,on=['product_name'],how='left')

,product_name,real_quantity_x,real_quantity_y,category
0,WORLD WAR 2 GLIDERS ASSTD DESIGNS,36102,2592,Home & Garden
1,WORLD WAR 2 GLIDERS ASSTD DESIGNS,36102,1728,Home & Garden
2,WORLD WAR 2 GLIDERS ASSTD DESIGNS,36102,1152,Home & Garden
3,WORLD WAR 2 GLIDERS ASSTD DESIGNS,36102,1152,Home & Garden
4,WORLD WAR 2 GLIDERS ASSTD DESIGNS,36102,1152,Home & Garden
...,...,...,...,...
17197,JUMBO STORAGE BAG SUKI,9610,1,"Bags, Luggage & Accessories"
17198,JUMBO STORAGE BAG SUKI,9610,1,"Bags, Luggage & Accessories"
17199,JUMBO STORAGE BAG SUKI,9610,1,"Bags, Luggage & Accessories"
17200,JUMBO STORAGE BAG SUKI,9610,0,"Bags, Luggage & Accessories"
17201,JUMBO STORAGE BAG SUKI,9610,0,"Bags, Luggage & Accessories"

In [50]:
ranking.drop_duplicates(keep='first',inplace=True)

In [51]:
ranking.groupby('category')['real_quantity_x'].sum()

category
Bags, Luggage & Accessories     80779
Home & Garden                  261406
Lights & Lighting               62736
Wedding , Party & Events        13995
Name: real_quantity_x, dtype: int64

In [34]:
data[0:30]

,product_name,real_quantity,category
107651,SMALL POPCORN HOLDER,4300,Home & Garden
229416,EMPIRE DESIGN ROSETTE,3906,NaN
273642,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,NaN
253075,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,Home & Garden
221405,SMALL CHINESE STYLE SCISSOR,3000,NaN
24280,ASSORTED COLOUR BIRD ORNAMENT,2880,Home & Garden
24277,ASSORTED COLOUR BIRD ORNAMENT,2880,Home & Garden
85135,PACK OF 60 PINK PAISLEY CAKE CASES,2700,Home & Garden
26448,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2592,Home & Garden
273641,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,2400,NaN
25494,GROW A FLYTRAP OR SUNFLOWER IN TIN,2400,Home & Garden
149197,PACK OF 12 SKULL TISSUES,2160,NaN
144494,RED HARMONICA IN BOX,2100,NaN
221404,SMALL CHINESE STYLE SCISSOR,2000,NaN
221403,SMALL CHINESE STYLE SCISSOR,2000,NaN
141015,GIN + TONIC DIET METAL SIGN,2000,Home & Garden
183501,GREEN VINTAGE SPOT BEAKER,1944,NaN
214416,PINK VINTAGE SPOT BEAKER,1944,Home & Garden
5073,WHITE HANGING HEART T-LIGHT HOLDER,1930,Lights & Lighting
138607,POPCORN HOLDER,1900,NaN
138611,POPCORN HOLDER,1900,NaN
214524,BLUE VINTAGE SPOT BEAKER,1878,NaN
162518,RAIN PONCHO RETROSPOT,1788,Home & Garden
26452,WORLD WAR 2 GLIDERS ASSTD DESIGNS,1728,Home & Garden
255987,LETTER SHAPE PENCIL SHARPENER,1600,NaN
144493,RED HARMONICA IN BOX,1540,NaN
221398,SMALL CHINESE STYLE SCISSOR,1500,NaN
16196,VINTAGE DOILY JUMBO BAG RED,1500,"Bags, Luggage & Accessories"
138466,POPCORN HOLDER,1500,NaN
73001,72 SWEETHEART FAIRY CAKE CASES,1440,Home & Garden

In [33]:
data.iloc[0:100].groupby('category')['category'].value_counts()

category                                 category
Bags, Luggage & Accessories              Bags, Luggage & Accessories                 4
Christmas                                Christmas                                   2
Home & Garden                            Home & Garden                              54
Lights & Lighting                        Lights & Lighting                           5
Manual                                   Manual                                      1
Office & School & Business & Industrial  Office & School & Business & Industrial     1
Toys & Gifts                             Toys & Gifts                                3
Name: category, dtype: int64